name: PrivateVaults
main: PrivateVaults\main
authors: Daniktheboss
version: 1.0.0
api: 2.0.0

commands:
  pv:
    description: "access private vaults"
    permission: pv

permissions:
  pv:
     default: true
     description: "Allows /pv"
